---
name: Build bos
on: # yamllint disable-line rule:truthy rule:comments
  schedule:
    # yamllint disable-line rule:comments
    - cron: "41 3 * * 2" # Every Tuesday at 3:41 AM UTC (bluefin at 1:00 AM UTC)
    # yamllint disable-line rule:comments
    - cron: "41 3 * * 0,1,3,4,5,6" # 3:41 UTC Monday-Saturday
  pull_request:
    branches:
      - master
  merge_group:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Project
    permissions:
      contents: read
    uses: ./.github/workflows/lint.yml

  build-image:
    name: Build Images
    needs: [lint]
    uses: ./.github/workflows/build-image.yml
    permissions:
      actions: read
      contents: read
      packages: write
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    strategy:
      fail-fast: false
      matrix:
        image_flavor: ["Desktop"]
    with:
      image_flavor: ${{ matrix.image_flavor }}
